# Generated by Django 5.2.4 on 2025-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_alter_tool_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="items",
        ),
        migrations.AlterField(
            model_name="tool",
            name="kind",
            field=models.CharField(max_length=20, verbose_name="종류"),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=20, verbose_name="이름"),
        ),
    ]
