# Generated by Django 5.2.4 on 2025-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="제목")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="posts/%Y%m%d", verbose_name="이미지"
                    ),
                ),
                ("content", models.CharField(max_length=100, verbose_name="내용")),
                ("interest", models.IntegerField(default=0, verbose_name="관심도")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="수정일"),
                ),
            ],
        ),
    ]
