# Generated by Django 5.2.4 on 2025-07-16 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="devtool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tools.tool",
                verbose_name="개발툴",
            ),
        ),
    ]
