# Generated by Django 5.2.4 on 2025-07-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starred", models.BooleanField(default=False, verbose_name="찜")),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.idea",
                        verbose_name="아이디어",
                    ),
                ),
            ],
        ),
    ]
