# Generated by Django 5.2.4 on 2025-07-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimgcontent",
            name="image",
            field=models.ImageField(upload_to="posts/images/%Y/%m/%d/"),
        ),
    ]
