# Generated by Django 5.2.4 on 2025-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("release", models.CharField(max_length=10)),
                ("genre", models.CharField(max_length=32)),
                ("rating", models.CharField(max_length=10)),
                ("runningTime", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("director", models.CharField(max_length=32)),
                ("actor", models.CharField(max_length=32)),
            ],
        ),
    ]
