# Generated by Django 5.2.4 on 2025-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_review_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("drama", "드라마"),
                    ("comedy", "코미디"),
                    ("thriller", "스릴러"),
                    ("horror", "공포"),
                    ("sf", "SF"),
                    ("fantasy", "판타지"),
                    ("romance", "멜로/로맨스"),
                    ("docu", "다큐멘터리"),
                ],
                max_length=32,
            ),
        ),
    ]
