# Generated by Django 5.2.4 on 2025-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_review_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("드라마", "드라마"),
                    ("코미디", "코미디"),
                    ("스릴러", "스릴러"),
                    ("공포", "공포"),
                    ("SF", "SF"),
                    ("판타지", "판타지"),
                    ("멜로/로맨스", "멜로/로맨스"),
                    ("다큐멘터리", "다큐멘터리"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="runningTime",
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
